customhost = "shreyadatabase.ckngqxj7tnaf.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "admin123"
customdb = "shreyadatabase"
custombucket = "shreya-pro2buck"
customregion = "us-east-1"
